### PR TITLE
Added an additional relevant choice for Yusuke's rank 6.

### PR DESCRIPTION
**Pull request by jammerware**
Thanks for making this tool, it's getting me through my first playthrough! I noticed a relevant choice for Yusuke that wasn't in there (probably because the source you got the data from missed it. Not your fault), so here's a PR that adds it. Use it if you want. Thanks again!

### CODE REVIEW

**Comment by neshield** [comment]
Thanks for contributing! Just want to be sure you confirmed this builds correctly?

**Comment by jammerware** [comment]
Yup, it ran fine for me locally with npm i && npm start. I just pushed an
additional commit because I realized my editor formatted with 4 space tabs
instead of 2 in my original commit. Looks good to go to me!

**Comment by neshield** [comment]
Okay, great! I need to confirm with my job that I'm allowed to actively work on open source projects, and then I can merge. Thanks for your help :)

Just wondering, are you using the site on Mobile or Desktop?

**Comment by jammerware** [comment]
I use it on both depending on where I'm sitting in my office :D

**Pull request merged**
